---
- name: Создание группы zabbix
  group:
    name: "{{ zabbix_agent_group }}"
    system: true
    state: present

- name: Создание пользователя zabbix и добавление его вгруппу
  user:
    name: "{{ zabbix_agent_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ zabbix_agent_group }}"
    createhome: false

- name: Создание дирректории с файлом конфигурации
  file:
    path: "/etc/zabbix-agent/"
    state: directory
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    mode: 0755

- name: Создание дирректории для логов агента
  file:
    path: /var/log/zabbix-agent
    state: directory
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    mode: 0755

- name: Создание временной дирриктории для закачки пакета
  file:
    path: "/tmp/zabbix_agent_{{ zabbix_agent_version }}"
    state: directory

- name: Загрузка пакета {{ zabbix_agent_package }}
  get_url:
    url: "{{ zabbix_agent_url }}"
    dest: "/tmp/{{ zabbix_agent_package }}"

- name: Распаковка пакета {{ zabbix_agent_package }}
  unarchive:
    copy: false
    src: "/tmp/{{ zabbix_agent_package }}"
    dest: "/tmp/zabbix_agent_{{ zabbix_agent_version }}"
    creates: "/tmp/zabbix_agent_{{ zabbix_agent_version }}/conf"

- name: Копирование исполняемых файлов агента
  copy:
    remote_src: yes
    src: "/tmp/zabbix_agent_{{ zabbix_agent_version }}/sbin/zabbix_agentd"
    dest: "/usr/local/bin/zabbix_agentd"
    mode: 0755
    owner: root
    group: root
  notify: restart zabbix-agent

- name: Копирование необходимых утилит
  copy:
    remote_src: yes
    src: "/tmp/zabbix_agent_{{ zabbix_agent_version }}/bin/{{ item }}"
    dest: "/usr/local/bin/"
    mode: 0644
    owner: root
    group: root
  with_items:
    - zabbix_get
    - zabbix_sender

- name: Копирование файла конфигурации агента
  template:
    src: zabbix_agentd.conf.j2
    dest: "/etc/zabbix-agent/zabbix-agent.conf"
    mode: 0644
  notify: restart zabbix-agent

- name: Копирование демона агента
  template:
    src: zabbix-agent.service.j2
    dest: "/etc/systemd/system/zabbix-agent.service"
    mode: 0644
  notify: restart zabbix-agent

- name: Добавление в автозагрузку и запуск агента
  systemd:
    daemon_reload: true
    name: zabbix-agent
    state: started
    enabled: true