---
- name: Закачка скрипта репозитория Gitlab-runner
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest: /tmp/gitlab-runner.script.deb.sh
    mode: 0744
  
- name: Добавление репозитория Gitlab-runner
  command: bash /tmp/gitlab-runner.script.deb.sh
  args:
    creates: "/etc/apt/sources.list.d/runner_gitlab-runner.list"
  become: true

- name: Установка GitLab-runner
  apt:
    name: gitlab-runner
    state: present
    update-cache: yes
  become: true